/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/compare": {
    /**
     * Compare Runs
     * @description Return the comparison between two persisted Run_Reports.
     */
    get: operations["compare_runs_api_compare_get"];
  };
  "/api/health": {
    /**
     * Health
     * @description Liveness probe used by the UI to detect Backend availability.
     */
    get: operations["health_api_health_get"];
  };
  "/api/models": {
    /**
     * List Models
     * @description List models reported by the configured Ollama_Server.
     *
     * Translates network/HTTP failures to ``502 ollama_unreachable``
     * so UI clients can branch on a well-known code.
     */
    get: operations["list_models_api_models_get"];
  };
  "/api/runs": {
    /**
     * List Runs
     * @description Return stored runs matching the supplied filters.
     */
    get: operations["list_runs_api_runs_get"];
    /**
     * Submit Run
     * @description Persist a new Run as ``pending`` and hand it to the supervisor.
     */
    post: operations["submit_run_api_runs_post"];
  };
  "/api/runs/{run_id}": {
    /**
     * Get Run
     * @description Return the full :class:`RunReport` for ``run_id``.
     */
    get: operations["get_run_api_runs__run_id__get"];
    /**
     * Delete Run
     * @description Delete a Run and its persisted artifacts (Requirement 12.5).
     */
    delete: operations["delete_run_api_runs__run_id__delete"];
  };
  "/api/runs/{run_id}/cancel": {
    /**
     * Cancel Run
     * @description Request cooperative cancellation of a live Run.
     */
    post: operations["cancel_run_api_runs__run_id__cancel_post"];
  };
  "/api/runs/{run_id}/report.md": {
    /**
     * Get Run Markdown
     * @description Return the Run_Report rendered as ``text/markdown``.
     */
    get: operations["get_run_markdown_api_runs__run_id__report_md_get"];
  };
  "/api/suites": {
    /**
     * List Suites
     * @description Return sorted suite names discovered under ``suites_dir``.
     */
    get: operations["list_suites_api_suites_get"];
  };
  "/api/suites/summaries": {
    /**
     * List Suite Summaries
     * @description Return lightweight metadata (name, case count, description) for every suite.
     *
     * Used by the UI's New Run page to annotate the suites multi-select
     * with case counts and rough-ETA estimates without pulling every
     * Test_Case. Results are emitted in the same order as
     * ``GET /api/suites``.
     */
    get: operations["list_suite_summaries_api_suites_summaries_get"];
  };
  "/api/suites/{name}": {
    /**
     * Get Suite
     * @description Return the full :class:`EvaluationSuite` matching ``name``.
     */
    get: operations["get_suite_api_suites__name__get"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /**
     * CancelRunResponse
     * @description Body of the 200 response from ``POST /api/runs/{id}/cancel``.
     */
    CancelRunResponse: {
      /** Run Id */
      run_id: string;
      /**
       * Status
       * @description The new status after the cancel flag is set.
       */
      status: string;
    };
    /**
     * ComparisonReport
     * @description Top-level Comparison_Report returned by :func:`compare`.
     *
     * ``metric_diffs`` and ``performance_diffs`` are lists (not dicts)
     * to match the design's §Data Models / Comparison_Report table and
     * because list ordering is stable across re-renderings in the UI
     * (Property 41). Ordering is deterministic: the lists are sorted
     * lexicographically by key tuple so two independent invocations on
     * equal inputs produce equal reports.
     */
    ComparisonReport: {
      /**
       * Metric Diffs
       * @description Per-``(model, metric)`` diffs over the intersection.
       */
      metric_diffs: components["schemas"]["MetricDiff"][];
      /**
       * Performance Diffs
       * @description Per-model performance diffs over the intersection.
       */
      performance_diffs: components["schemas"]["PerformanceDiff"][];
      /**
       * Run A
       * @description ``RunReport.run_id`` of the base Run.
       */
      run_a: string;
      /**
       * Run B
       * @description ``RunReport.run_id`` of the comparison Run.
       */
      run_b: string;
    };
    /**
     * ConfigFile
     * @description The on-disk Config_File loaded via the ``--config`` CLI flag.
     *
     * A ``ConfigFile`` carries process-wide settings (Ollama base URL, where
     * to discover suites, where to write reports, logging verbosity, and
     * dataset-sourcing defaults) plus an embedded :class:`RunConfig`
     * describing the Run to execute.
     *
     * ``hf_cache_dir`` defaults to ``None`` so the Backend can fall back to
     * the HuggingFace ``datasets`` library's own cache resolution (``$HF_HOME``
     * or ``~/.cache/huggingface``) without the Config_File having to encode
     * platform-specific paths.
     */
    ConfigFile: {
      /**
       * Dataset Mode
       * @description Default ``dataset_mode`` for adapter-backed Evaluation_Suites (Requirement 17.3). Individual suite files may override this per-suite. ``local`` means read from disk; ``remote`` means stream from the HuggingFace Hub at Run time.
       * @default local
       * @enum {string}
       */
      dataset_mode?: "local" | "remote";
      /**
       * Hf Cache Dir
       * @description Directory used by the HuggingFace ``datasets`` library for its on-disk cache. When ``None`` the library's own default is used (``$HF_HOME`` or ``~/.cache/huggingface``).
       */
      hf_cache_dir?: string | null;
      /**
       * Log Level
       * @description Global log verbosity (Requirement 10.6). The CLI ``--log-level`` flag overrides this value at runtime.
       * @default info
       * @enum {string}
       */
      log_level?: "debug" | "info" | "warn" | "error";
      /**
       * Ollama Base Url
       * @description Base URL of the Ollama_Server (Requirement 1.1). Must be an absolute ``http://`` or ``https://`` URL.
       * @default http://localhost:11434
       */
      ollama_base_url?: string;
      /**
       * Output Dir
       * Format: path
       * @description Directory where Run_Reports (``runs/{run_id}/report.json`` and ``report.md``) are written (Requirement 8.1).
       */
      output_dir?: string;
      /** @description Run-level configuration (models, suites, concurrency, ...). */
      run: components["schemas"]["RunConfig"];
      /**
       * Suites Dir
       * Format: path
       * @description Directory containing Evaluation_Suite files to discover at Run start (Requirement 3.1). Required; there is no sensible default because evaluation content is user-supplied.
       */
      suites_dir: string;
    };
    /**
     * ErrorSummaryEntry
     * @description One entry in :class:`RunReport.error_summary` (Requirement 11.3).
     *
     * Emitted once per ``TestCaseResult`` whose ``status`` is ``error`` or
     * ``timeout``. The entry repeats the identifying tuple from the
     * underlying result so the summary section can be rendered on its own
     * without cross-referencing ``RunReport.results`` (Property 22).
     */
    ErrorSummaryEntry: {
      /**
       * Error Message
       * @description Human-readable error message from the underlying result.
       */
      error_message: string;
      /**
       * Model
       * @description Ollama model tag the failed execution ran against.
       */
      model: string;
      /**
       * Repetition
       * @description 1-indexed repetition number of the failed execution.
       */
      repetition: number;
      /**
       * Suite
       * @description Evaluation_Suite name the failed test case belongs to.
       */
      suite: string;
      /**
       * Test Case Id
       * @description ``TestCase.id`` of the failed execution.
       */
      test_case_id: string;
    };
    /**
     * EvaluationSuite
     * @description A named, versioned collection of :class:`TestCase` objects.
     *
     * A suite is the primary on-disk artifact authored by users (YAML or JSON;
     * see ``suites/loader.py``) and the unit of filtering at Run time
     * (Requirement 3.6). Suites must have a non-empty ``name``, a non-empty
     * ``test_cases`` list, and every ``test_cases[i].id`` must be unique
     * within the suite (Requirement 3.3).
     */
    EvaluationSuite: {
      /** @description Default generation parameters for every TestCase in this suite. */
      defaults?: components["schemas"]["GenerationDefaults"];
      /**
       * Description
       * @description Optional free-form description shown in the UI.
       */
      description?: string | null;
      /**
       * Name
       * @description Human-readable suite name, used by ``RunConfig.suites``.
       */
      name: string;
      /**
       * Test Cases
       * @description Ordered, non-empty list of test cases with unique ids.
       */
      test_cases: components["schemas"]["TestCase"][];
      /**
       * Version
       * @description Authoring version string; informational only in v1.
       * @default 1.0
       */
      version?: string;
    };
    /**
     * GenerationDefaults
     * @description Run-level defaults for Ollama generation parameters.
     *
     * A ``TestCase`` may override any of these fields individually. When a
     * ``TestCase`` leaves a field unset (``None``), the runner falls back to
     * the corresponding value from ``GenerationDefaults`` (see Requirement 5.4
     * and Property 7 in the design document).
     */
    GenerationDefaults: {
      /**
       * Max Tokens
       * @description Maximum tokens to generate (``options.num_predict``). ``None`` means use the model's default.
       */
      max_tokens?: number | null;
      /**
       * Stop Sequences
       * @description Default ``options.stop`` sequences applied to every Test_Case.
       */
      stop_sequences?: string[];
      /**
       * Temperature
       * @description Sampling temperature passed to Ollama (``options.temperature``).
       * @default 0
       */
      temperature?: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * MetricAggregate
     * @description Mean and population stddev for a single ``(model, metric)`` pair.
     *
     * Keyed by metric name inside :class:`ModelAggregate.metric_aggregates`.
     * The aggregation itself is computed by :mod:`runner.aggregate` using
     * :func:`statistics.fmean` and :func:`statistics.pstdev` (Property 15).
     *
     * ``stddev`` is the *population* standard deviation, not the sample
     * variant. For a single-repetition Run (``count == 1``) this is the
     * well-defined value ``0``; sample stddev would be undefined. Sticking
     * to pstdev everywhere means the aggregator never has to special-case
     * ``count == 1``.
     */
    MetricAggregate: {
      /**
       * Count
       * @description Number of per-repetition samples that fed this aggregate. Must be >= 0.
       */
      count: number;
      /**
       * Mean
       * @description Arithmetic mean of the per-repetition scores.
       */
      mean: number;
      /**
       * Metric
       * @description Metric name this aggregate corresponds to.
       */
      metric: string;
      /**
       * Stddev
       * @description Population standard deviation of the per-repetition scores. Must be >= 0.
       */
      stddev: number;
    };
    /**
     * MetricConfig
     * @description Configuration for a single metric attached to a :class:`TestCase`.
     *
     * Different built-in metrics accept different parameters (``exact-match``
     * takes ``case_sensitive`` / ``trim``; ``regex-match`` takes ``pattern`` /
     * ``flags``; ``json-schema-valid`` takes ``schema``; ``length-range`` takes
     * ``min`` / ``max``; ``llm-as-judge`` takes ``rubric`` / ``judge_model``;
     * and so on). Rather than enumerating every metric's schema at the suite
     * layer, ``MetricConfig`` exposes a ``name`` plus a generic ``params``
     * mapping. The concrete metric implementations (``metrics/builtin.py``,
     * ``metrics/judge.py``) are responsible for validating the contents of
     * ``params`` themselves.
     *
     * ``extra="forbid"`` is still applied here — the only two top-level fields
     * permitted are ``name`` and ``params``. This preserves the spec rule that
     * every suite model rejects unknown fields while still letting metrics
     * carry arbitrary structured configuration.
     */
    MetricConfig: {
      /**
       * Name
       * @description Identifier of a registered metric (e.g. 'exact-match').
       */
      name: string;
      /**
       * Params
       * @description Metric-specific parameters passed verbatim to the metric implementation. Validated by the metric itself, not here.
       */
      params?: {
        [key: string]: unknown;
      };
    };
    /**
     * MetricDiff
     * @description One row of :class:`ComparisonReport.metric_diffs`.
     *
     * ``diff`` is ``mean_b - mean_a``. Positive means Run B scored
     * higher than Run A on the given metric; negative means the
     * opposite. The field is a ``float`` (not ``float | None``)
     * because the enclosing keyset is the *intersection* — a
     * ``MetricDiff`` is only emitted when both reports have a value.
     */
    MetricDiff: {
      /**
       * Diff
       * @description ``mean_b - mean_a``.
       */
      diff: number;
      /**
       * Mean A
       * @description Mean score in Run A.
       */
      mean_a: number;
      /**
       * Mean B
       * @description Mean score in Run B.
       */
      mean_b: number;
      /**
       * Metric
       * @description Metric name.
       */
      metric: string;
      /**
       * Model
       * @description Model tag the metric was scored for.
       */
      model: string;
    };
    /**
     * MetricResult
     * @description Score produced by a single metric for a single Test_Case execution.
     *
     * A ``MetricResult`` is always carried on a :class:`TestCaseResult`,
     * even when the metric itself raises during scoring (Requirement 7.5).
     * In the error path the runner sets ``error`` to the raised message and
     * ``passed`` to ``False``; ``score`` is still required and the runner
     * records ``0.0`` by convention so the aggregation code can operate on
     * a uniform numeric field.
     *
     * ``details`` is a free-form mapping reserved for metric-specific
     * context (for example, the captured response for the
     * ``response-capture`` metric, the matched regex group for
     * ``regex-match``, or the JSON-Schema validation errors for
     * ``json-schema-valid``). It intentionally has no internal schema here.
     */
    MetricResult: {
      /**
       * Details
       * @description Metric-specific structured context. Free-form; validated by the metric implementation, not here.
       */
      details?: {
        [key: string]: unknown;
      };
      /**
       * Error
       * @description Populated when the metric raised during scoring (Requirement 7.5). ``passed`` is ``False`` in that case and the Run continues with the remaining metrics.
       */
      error?: string | null;
      /**
       * Name
       * @description Identifier of the metric that produced this result.
       */
      name: string;
      /**
       * Passed
       * @description Pass/fail classification against the metric's threshold (Requirement 7.4).
       */
      passed: boolean;
      /**
       * Score
       * @description Numeric score in the metric-defined range (Requirement 7.3).
       */
      score: number;
      /**
       * Threshold
       * @description Threshold used by the metric to classify ``score`` as passed. ``None`` for metrics that do not parametrise a threshold (e.g. boolean metrics).
       */
      threshold?: number | null;
    };
    /**
     * ModelAggregate
     * @description Aggregate statistics for a single evaluated model.
     *
     * One ``ModelAggregate`` is produced per entry in
     * ``RunConfig.models``. Counters (``passed``/``failed``/``errored``/
     * ``timed_out``) sum the per-execution ``TestCaseResult.status`` values
     * filtered to this model. Performance means average across every
     * ``(test_case, repetition)`` for this model; ``mean_ttft_ms`` and
     * ``mean_tokens_per_second`` are nullable because the underlying
     * per-execution fields are nullable (Requirement 6.5).
     *
     * ``metric_aggregates`` is keyed by metric name so the UI and
     * comparison report can look up a metric without scanning a list
     * (Property 19).
     */
    ModelAggregate: {
      /**
       * Errored
       * @description Number of executions with ``status == 'error'``.
       */
      errored: number;
      /**
       * Failed
       * @description Number of executions with ``status == 'fail'``.
       */
      failed: number;
      /**
       * Mean Tokens Per Second
       * @description Mean tokens-per-second, averaged across executions with a non-``None`` ``tokens_per_second``. ``None`` when no execution produced the derived value.
       */
      mean_tokens_per_second: number | null;
      /**
       * Mean Total Ms
       * @description Mean total response time in milliseconds, averaged across every execution for this model.
       */
      mean_total_ms: number;
      /**
       * Mean Ttft Ms
       * @description Mean time-to-first-token in milliseconds, averaged across executions with a non-``None`` ``ttft_ms``. ``None`` when no execution reported TTFT.
       */
      mean_ttft_ms: number | null;
      /**
       * Metric Aggregates
       * @description Per-metric mean/stddev aggregates keyed by metric name.
       */
      metric_aggregates: {
        [key: string]: components["schemas"]["MetricAggregate"];
      };
      /**
       * Model
       * @description Ollama model tag these aggregates describe.
       */
      model: string;
      /**
       * Passed
       * @description Number of executions with ``status == 'pass'``.
       */
      passed: number;
      /**
       * Timed Out
       * @description Number of executions with ``status == 'timeout'``.
       */
      timed_out: number;
    };
    /**
     * ModelInfo
     * @description Identifying metadata for an evaluated Ollama model.
     *
     * Populated from the Ollama_Server's ``/api/tags`` response at Run
     * start (Requirement 2.5). ``digest`` and ``parameter_size`` are
     * nullable because some Ollama_Server versions omit them and because
     * a Run submitted against an inventory that is still pulling a model
     * may run before the digest is observable.
     */
    ModelInfo: {
      /**
       * Digest
       * @description Content-addressed digest reported by the Ollama_Server.
       */
      digest?: string | null;
      /**
       * Name
       * @description Ollama model tag, e.g. ``"llama3:8b"``.
       */
      name: string;
      /**
       * Parameter Size
       * @description Human-readable parameter count (e.g. ``"8B"``).
       */
      parameter_size?: string | null;
    };
    /**
     * PerformanceDiff
     * @description One row of :class:`ComparisonReport.performance_diffs`.
     *
     * Populated per model present in both reports. ``*_tps_*`` fields
     * are nullable because the underlying per-model mean is nullable
     * (Requirement 6.5). ``tps_diff`` is ``None`` when either side is
     * ``None``; ``total_ms_diff`` is always a concrete ``float``
     * because ``mean_total_ms`` is non-nullable on
     * :class:`ModelAggregate`.
     */
    PerformanceDiff: {
      /**
       * Mean Tokens Per Second A
       * @description Run A's mean tokens-per-second for this model.
       */
      mean_tokens_per_second_a: number | null;
      /**
       * Mean Tokens Per Second B
       * @description Run B's mean tokens-per-second for this model.
       */
      mean_tokens_per_second_b: number | null;
      /**
       * Mean Total Ms A
       * @description Run A's mean total response time for this model (ms).
       */
      mean_total_ms_a: number;
      /**
       * Mean Total Ms B
       * @description Run B's mean total response time for this model (ms).
       */
      mean_total_ms_b: number;
      /**
       * Model
       * @description Model tag.
       */
      model: string;
      /**
       * Total Ms Diff
       * @description ``mean_total_ms_b - mean_total_ms_a``.
       */
      total_ms_diff: number;
      /**
       * Tps Diff
       * @description ``mean_tokens_per_second_b - mean_tokens_per_second_a``; ``None`` when either side is ``None``.
       */
      tps_diff: number | null;
    };
    /**
     * PerformanceMetrics
     * @description Per-execution timing and token-count measurements.
     *
     * ``ttft_ms`` and the token-count fields are nullable because the
     * Ollama_Server does not always populate them (Requirement 6.5). A
     * missing value must not be coerced to ``0`` — ``0`` is a valid
     * measurement that means "zero tokens" or "no delay" and would be
     * indistinguishable from "unknown" if we silently defaulted to it.
     *
     * ``tokens_per_second`` is derived by the runner from ``response_tokens``
     * and ``total_ms`` (Requirement 6.4, Property 10). It is stored on the
     * model rather than recomputed on demand so that reports remain stable
     * even if the derivation rule changes in a future version.
     */
    PerformanceMetrics: {
      /**
       * Prompt Tokens
       * @description Prompt token count reported by the Ollama_Server (Requirement 6.3). ``None`` when the server omitted it.
       */
      prompt_tokens?: number | null;
      /**
       * Response Tokens
       * @description Response token count reported by the Ollama_Server (Requirement 6.3). ``None`` when the server omitted it.
       */
      response_tokens?: number | null;
      /**
       * Tokens Per Second
       * @description Derived throughput: ``response_tokens / (total_ms / 1000)`` (Requirement 6.4). ``None`` when ``response_tokens`` is ``None`` or ``total_ms`` is 0.
       */
      tokens_per_second?: number | null;
      /**
       * Total Ms
       * @description Total response time from request dispatch to the final chunk, in milliseconds (Requirement 6.2).
       */
      total_ms: number;
      /**
       * Ttft Ms
       * @description Wall-clock time from request dispatch to the first streamed chunk, in milliseconds (Requirement 6.1). ``None`` when the server omitted the timing (Requirement 6.5).
       */
      ttft_ms?: number | null;
    };
    /**
     * RunConfig
     * @description Run-level configuration for a single Run.
     *
     * ``RunConfig`` is the body the Backend_API accepts for
     * ``POST /api/runs`` and is also embedded in :class:`ConfigFile` as the
     * ``run:`` section. A ``RunConfig`` is serialised verbatim into every
     * ``RunReport`` so runs are reproducible from their report alone
     * (Requirement 8.4).
     *
     * Validators enforce the numeric ranges specified in the Requirements
     * document and reject empty ``models`` / ``suites`` lists early, before
     * any Ollama_Server call is made.
     */
    RunConfig: {
      /**
       * Concurrency
       * @description Maximum number of in-flight Ollama_Server requests during this Run. Must be >= 1 (Requirement 5.5).
       * @default 1
       */
      concurrency?: number;
      /**
       * Judge Model
       * @description Ollama model tag used by any configured ``llm-as-judge`` metric. ``None`` means no judge model is configured; metrics that require one will raise a validation error at Run start.
       */
      judge_model?: string | null;
      /**
       * Models
       * @description Ollama model tags to evaluate in this Run (e.g. 'llama3:8b'). Must contain at least one model (Requirement 2.2).
       */
      models: string[];
      /**
       * Ollama Timeout S
       * @description Per-request timeout in seconds applied to every Ollama_Server call made during this Run (Requirement 1.4). Must be > 0.
       * @default 120
       */
      ollama_timeout_s?: number;
      /**
       * Pull Missing Models
       * @description If true, instruct the Ollama_Server to pull any requested Model that is not already available (Requirement 2.4).
       * @default false
       */
      pull_missing_models?: boolean;
      /**
       * Repetitions
       * @description Number of times each Test_Case is executed per Model. Must be >= 1 (Requirement 5.2).
       * @default 1
       */
      repetitions?: number;
      /**
       * Retry Max Attempts
       * @description Number of *additional* retry attempts per Test_Case execution on retryable network errors (Requirement 11.1). Must be >= 0. A value of 0 disables retries entirely.
       * @default 2
       */
      retry_max_attempts?: number;
      /**
       * Suites
       * @description Names of Evaluation_Suites to run. Must contain at least one name (Requirement 3.1).
       */
      suites: string[];
      /**
       * Tag Filter
       * @description Optional Test_Case tag filter (Requirement 3.6). When empty, every Test_Case in the selected suites is included. When non-empty, only Test_Cases whose ``tags`` intersect this list are selected.
       */
      tag_filter?: string[];
    };
    /**
     * RunReport
     * @description Top-level Run_Report persisted to disk and returned by the REST API.
     *
     * A ``RunReport`` is the single source of truth for a completed Run
     * (Requirement 8.4): it embeds the full submitted :class:`ConfigFile`,
     * the identifying metadata for every evaluated model, every
     * per-execution result, the per-model aggregates, and an error
     * summary. Property 16 (Run_Report completeness) asserts this
     * invariant; Property 18 (round-trip) asserts that
     * ``RunReport.model_validate_json(r.model_dump_json()) == r`` for
     * every valid ``r``.
     *
     * ``status`` is a five-value literal covering the full state machine:
     *
     * * ``pending`` — the Run has been created but dispatch has not started.
     * * ``running`` — at least one execution is in flight or queued.
     * * ``completed`` — every planned execution has produced a result.
     * * ``aborted`` — the Run was stopped by a cancel request or signal
     *   before all planned executions completed (Requirement 11.4).
     * * ``failed`` — the Run could not start (e.g. missing models in
     *   preflight, Property 5) and no per-execution results exist.
     *
     * The ``ended_at >= started_at`` invariant is enforced in a model
     * validator rather than field-by-field because it is a cross-field
     * constraint (Property 16).
     */
    RunReport: {
      /**
       * Aggregates
       * @description One ``ModelAggregate`` per evaluated model (Requirement 8.2).
       */
      aggregates: components["schemas"]["ModelAggregate"][];
      /**
       * Backend Version
       * @description Version string of the Backend that produced this report.
       */
      backend_version: string;
      /** @description Full submitted ``ConfigFile`` (Requirement 8.4). */
      config: components["schemas"]["ConfigFile"];
      /**
       * Ended At
       * @description UTC timestamp when the Run reached a terminal state. ``None`` while the Run is still ``pending`` or ``running``.
       */
      ended_at: string | null;
      /**
       * Error Summary
       * @description One entry per result with ``status`` in ``{'error', 'timeout'}`` (Requirement 11.3).
       */
      error_summary: components["schemas"]["ErrorSummaryEntry"][];
      /**
       * Models
       * @description One ``ModelInfo`` per evaluated model (Requirement 2.5).
       */
      models: components["schemas"]["ModelInfo"][];
      /**
       * Ollama Version
       * @description Ollama_Server version string at Run start. ``None`` when the Backend could not reach the server before failing.
       */
      ollama_version: string | null;
      /**
       * Results
       * @description One ``TestCaseResult`` per ``(model, test_case, repetition)``.
       */
      results: components["schemas"]["TestCaseResult"][];
      /**
       * Run Id
       * @description Unique identifier for this Run (Property 25). Must be non-empty.
       */
      run_id: string;
      /**
       * Started At
       * Format: date-time
       * @description UTC timestamp when the Run started.
       */
      started_at: string;
      /**
       * Status
       * @description Terminal or in-flight state of the Run (see class docstring).
       * @enum {string}
       */
      status: "pending" | "running" | "completed" | "aborted" | "failed";
    };
    /**
     * SubmitRunResponse
     * @description Body of the 201 response from ``POST /api/runs`` (Requirement 13.3).
     */
    SubmitRunResponse: {
      /**
       * Run Id
       * @description Identifier of the newly queued Run.
       */
      run_id: string;
      /**
       * Status
       * @description Initial status; always ``pending``.
       */
      status: string;
    };
    /**
     * SuiteSummary
     * @description Lightweight metadata for a single discovered Evaluation_Suite.
     *
     * Surfaced by ``GET /api/suites/summaries`` so clients (notably the
     * UI's New Run page) can render per-suite case counts and a time
     * estimate without issuing N full-suite fetches. Returning only the
     * counts (not the full ``test_cases`` list) is a ~100× payload
     * reduction for suites like ``mmlu`` (180 KB → ~100 bytes).
     *
     * The field set is intentionally minimal; callers that need any
     * additional metadata can still issue the targeted
     * ``GET /api/suites/{name}`` fetch.
     */
    SuiteSummary: {
      /**
       * Description
       * @description Optional free-form description copied from the suite file.
       */
      description?: string | null;
      /**
       * Name
       * @description Unique suite name (same identifier as ``GET /api/suites``).
       */
      name: string;
      /**
       * Test Case Count
       * @description Number of Test_Cases contained in the suite.
       */
      test_case_count: number;
    };
    /**
     * TestCase
     * @description A single evaluation unit within an :class:`EvaluationSuite`.
     *
     * Each test case carries a prompt to send to the model, optional metadata
     * (system prompt, expected output, reference data, tags), optional
     * per-case generation overrides, and a non-empty list of
     * :class:`MetricConfig` entries describing how the response should be
     * scored.
     *
     * Validators enforce:
     *
     * * ``prompt`` is non-empty (Requirement 3.3).
     * * ``metrics`` contains at least one entry (Requirement 3.3).
     *
     * Unknown fields are rejected by ``ConfigDict(extra="forbid")`` so typos
     * in user-authored suites surface as validation errors rather than being
     * silently ignored (Requirement 3.5).
     */
    TestCase: {
      /**
       * Expected Output
       * @description Optional canonical answer used by exact/regex metrics.
       */
      expected_output?: string | null;
      /**
       * Id
       * @description Stable identifier, unique within the enclosing suite.
       */
      id: string;
      /**
       * Max Tokens
       * @description Per-case ``num_predict`` override. ``None`` means use defaults.
       */
      max_tokens?: number | null;
      /**
       * Metrics
       * @description Scoring configuration. Must contain at least one entry.
       */
      metrics: components["schemas"]["MetricConfig"][];
      /**
       * Prompt
       * @description User prompt sent to the Ollama model. Must be non-empty.
       */
      prompt: string;
      /**
       * Reference Data
       * @description Arbitrary structured context consumed by specific metrics.
       */
      reference_data?: {
        [key: string]: unknown;
      } | null;
      /**
       * Stop Sequences
       * @description Per-case ``stop`` override. ``None`` (not ``[]``) means fall back to the run-level defaults; ``[]`` explicitly clears them.
       */
      stop_sequences?: string[] | null;
      /**
       * System Prompt
       * @description Optional system prompt prepended to the request.
       */
      system_prompt?: string | null;
      /**
       * Tags
       * @description Free-form tags for filtering at Run time (Requirement 3.6).
       */
      tags?: string[];
      /**
       * Temperature
       * @description Per-case sampling temperature override. ``None`` means fall back to the suite/run defaults.
       */
      temperature?: number | null;
    };
    /**
     * TestCaseResult
     * @description Outcome of a single ``(model, test_case, repetition)`` execution.
     *
     * ``status`` is a four-value literal rather than a boolean because a
     * Run distinguishes four outcome classes in both the report and the
     * event stream (Property 9):
     *
     * * ``pass`` — every configured metric classified the response as passing.
     * * ``fail`` — at least one metric classified the response as failing.
     * * ``error`` — the Ollama_Server call itself failed after all retries,
     *   or a metric raised in a way that the runner treats as a hard error.
     * * ``timeout`` — the Ollama_Server call exceeded ``ollama_timeout_s``.
     *
     * ``repetition`` is 1-indexed (the first repetition is ``1``, not ``0``)
     * so that the value can be displayed to users without re-indexing and
     * so that ``repetition <= RunConfig.repetitions`` is the natural bound.
     */
    TestCaseResult: {
      /**
       * Error Message
       * @description Human-readable error message for ``error``/``timeout`` outcomes. ``None`` for ``pass``/``fail``.
       */
      error_message?: string | null;
      /**
       * Metrics
       * @description One ``MetricResult`` per configured metric on the test case, in the order declared on the ``TestCase``.
       */
      metrics: components["schemas"]["MetricResult"][];
      /**
       * Model
       * @description Ollama model tag this execution ran against.
       */
      model: string;
      /** @description Timing and token-count measurements for this execution. */
      performance: components["schemas"]["PerformanceMetrics"];
      /**
       * Repetition
       * @description 1-indexed repetition number for this ``(model, test_case)`` pair. Must be >= 1.
       */
      repetition: number;
      /**
       * Response
       * @description Raw model response text, when available. ``None`` for ``error``/``timeout`` outcomes that never produced output.
       */
      response?: string | null;
      /**
       * Status
       * @description Four-valued outcome (see class docstring).
       * @enum {string}
       */
      status: "pass" | "fail" | "error" | "timeout";
      /**
       * Suite
       * @description Name of the Evaluation_Suite the test case belongs to.
       */
      suite: string;
      /**
       * Test Case Id
       * @description ``TestCase.id`` within the enclosing suite.
       */
      test_case_id: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Compare Runs
   * @description Return the comparison between two persisted Run_Reports.
   */
  compare_runs_api_compare_get: {
    parameters: {
      query: {
        /** @description Run id of the base run. */
        a: string;
        /** @description Run id of the comparison run. */
        b: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["ComparisonReport"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Health
   * @description Liveness probe used by the UI to detect Backend availability.
   */
  health_api_health_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  /**
   * List Models
   * @description List models reported by the configured Ollama_Server.
   *
   * Translates network/HTTP failures to ``502 ollama_unreachable``
   * so UI clients can branch on a well-known code.
   */
  list_models_api_models_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
    };
  };
  /**
   * List Runs
   * @description Return stored runs matching the supplied filters.
   */
  list_runs_api_runs_get: {
    parameters: {
      query?: {
        model?: string | null;
        suite?: string | null;
        status?: string | null;
        since?: string | null;
        until?: string | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": {
              [key: string]: unknown;
            }[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Submit Run
   * @description Persist a new Run as ``pending`` and hand it to the supervisor.
   */
  submit_run_api_runs_post: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RunConfig"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        content: {
          "application/json": components["schemas"]["SubmitRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Run
   * @description Return the full :class:`RunReport` for ``run_id``.
   */
  get_run_api_runs__run_id__get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["RunReport"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Delete Run
   * @description Delete a Run and its persisted artifacts (Requirement 12.5).
   */
  delete_run_api_runs__run_id__delete: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        content: never;
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Cancel Run
   * @description Request cooperative cancellation of a live Run.
   */
  cancel_run_api_runs__run_id__cancel_post: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["CancelRunResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * Get Run Markdown
   * @description Return the Run_Report rendered as ``text/markdown``.
   */
  get_run_markdown_api_runs__run_id__report_md_get: {
    parameters: {
      path: {
        run_id: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  /**
   * List Suites
   * @description Return sorted suite names discovered under ``suites_dir``.
   */
  list_suites_api_suites_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": string[];
        };
      };
    };
  };
  /**
   * List Suite Summaries
   * @description Return lightweight metadata (name, case count, description) for every suite.
   *
   * Used by the UI's New Run page to annotate the suites multi-select
   * with case counts and rough-ETA estimates without pulling every
   * Test_Case. Results are emitted in the same order as
   * ``GET /api/suites``.
   */
  list_suite_summaries_api_suites_summaries_get: {
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["SuiteSummary"][];
        };
      };
    };
  };
  /**
   * Get Suite
   * @description Return the full :class:`EvaluationSuite` matching ``name``.
   */
  get_suite_api_suites__name__get: {
    parameters: {
      path: {
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["EvaluationSuite"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
